#%RAML 1.0 Library
types:
  hosAvailableHours:
    type: object 
    properties:
      Envelope:
        type: object 
        properties:
          Header:
            type: object 
            properties:
              TMobileCommHeader:
                type: object
                properties:
                  NetworkID: string
                  __prefix: string
              TTMHeader: 
                type: object 
                properties:
                  DSN: string
                  Password: string
                  Schema: string
                  Username: string
                  __prefix: string
              __prefix: string
          Body: 
            type: object 
            properties:
              SendDriverHOSAvailableHours:
                type: object
                properties:
                  DriverId: string
                  OnDutyHoursAvailToday: string
                  DrivingHoursAvailToday: string
                  Hour24ResetDate: string
                  Hour34ResetDate?: string
                  Hour72ResetDate?: string
                  __prefix: string
              __prefix: string
          _xmlns:soapenv: string
          _xmlns:urn: string
          _xmlns:urn1: string
          _xmlns:urn2: string
          __prefix: string
                  



                   
                 
