#%RAML 1.0 Library
types:
  SendMessage:
    type: object
    properties:
      Envelope:
        type: object
        properties:
          Body: 
            type: object
            properties:
              SendMessagesResponse:
                type: object
                properties:
                  return:
                    type: object
                    properties:
                      item:
                        type: object
                        properties:
                          ErrorCode: string
                          ErrorMessage: string
                          Success: string
                  _xmlns:NS1: string
                  __prefix: string

              _SOAP-ENV:encodingStyle: string
              __prefix: string

          _xmlns:SOAP-ENV: string
          _xmlns:xsd: string
          _xmlns:xsi: string
          _xmlns:SOAP-ENC: string
          __prefix: string
                  